// <auto-generated />
using System;
using FinalProjectASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectASP.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectASP.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("Code")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeparture")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FinalProjectASP.Models.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLeg")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChangeStatus")
                        .HasColumnType("bit");

                    b.Property<int>("NextLegs")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Legs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLeg = 1,
                            IsChangeStatus = false,
                            NextLegs = 2,
                            Number = 1,
                            WaitTime = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentLeg = 2,
                            IsChangeStatus = false,
                            NextLegs = 4,
                            Number = 2,
                            WaitTime = 5
                        },
                        new
                        {
                            Id = 3,
                            CurrentLeg = 4,
                            IsChangeStatus = false,
                            NextLegs = 8,
                            Number = 3,
                            WaitTime = 6
                        },
                        new
                        {
                            Id = 4,
                            CurrentLeg = 8,
                            IsChangeStatus = false,
                            NextLegs = 272,
                            Number = 4,
                            WaitTime = 7
                        },
                        new
                        {
                            Id = 5,
                            CurrentLeg = 16,
                            IsChangeStatus = false,
                            NextLegs = 96,
                            Number = 5,
                            WaitTime = 4
                        },
                        new
                        {
                            Id = 6,
                            CurrentLeg = 32,
                            IsChangeStatus = true,
                            NextLegs = 128,
                            Number = 6,
                            WaitTime = 7
                        },
                        new
                        {
                            Id = 7,
                            CurrentLeg = 64,
                            IsChangeStatus = true,
                            NextLegs = 128,
                            Number = 7,
                            WaitTime = 8
                        },
                        new
                        {
                            Id = 8,
                            CurrentLeg = 128,
                            IsChangeStatus = true,
                            NextLegs = 8,
                            Number = 8,
                            WaitTime = 2
                        });
                });

            modelBuilder.Entity("FinalProjectASP.Models.Logger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GetIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GetOut")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegId");

                    b.ToTable("Loggers");
                });

            modelBuilder.Entity("FinalProjectASP.Models.Logger", b =>
                {
                    b.HasOne("FinalProjectASP.Models.Leg", "Leg")
                        .WithMany()
                        .HasForeignKey("LegId");

                    b.Navigation("Leg");
                });
#pragma warning restore 612, 618
        }
    }
}
